# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "HIBIT 2020"
email: "hibit2020@gmail.com"
description: "HIBIT 2020"
baseurl: ""
url: "https://hibit2020.sabanciuniv.edu/"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "HIBIT 2020 Organization Committee"
organizerAlternateName: "HIBIT 2020 Organization Committee"
organizerDescription: "Scientists organizing conference for scientists."
organizerEmail: "hibit2020@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://hibit2020.sabanciuniv.edu"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@hibit2020"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/logistics/", text: "Logistics"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Submit Abstract"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Submit Abstract"}

# Hero Block
heroImage: "ist2.jpg"
heroTitle: "HIBIT <typeout> 2020"
eventDate: "3-5 September, 2020"
typeoutTextValues: '""'
typeoutFallback: ""
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Submit Abstract"}
 - {permalink: "/#tickets", text: "Register"}

# About Block
aboutTitle: "About HIBIT"
aboutBlock:
 - {title: "13th The International Symposium on Health Informatics and Bioinformatics", image: "conference.jpg", text: "The International Symposium on Health Informatics and Bioinformatics, (HIBIT), now in its thirteenth year HIBIT 2020, aims to bring together academics, researchers and practitioners who work in these popular and fulfilling areas and to create the much-needed synergy among medical, biological and information technology sectors. HIBIT is one of the few conferences emphasizing such synergy. HIBIT provides a forum for discussion, exploration and development of both theoretical and practical aspects of health informatics and bioinformatics and a chance to follow current research in this area by networking with other bioinformatician." }
#  - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
#  - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "library.jpg"
statisticBlock:
 - {count: "300", prefix: "~", specialCharacter: "", info: "expected attendees", detail: "from everywhere"}
 - {count: "3", prefix: "", specialCharacter: "", info: "days", detail: "of solid science"}
 - {count: "3", prefix: "", specialCharacter: "", info: "keynote speakers", detail: "from USA and Europe"}
 - {count: "8", prefix: ">", specialCharacter: "", info: "invited speakers", detail: ""}
 - {count: "10", prefix: "~", specialCharacter: "", info: "selected talks", detail: ""}
 - {count: "100", prefix: "~", specialCharacter: "", info: "posters", detail: ""}

# Latest News Block
latestNewsTitle: "Latest news"

# Keynote Speakers Block
keynoteSpeakersImage: "bridge.jpg"
keynoteSpeakersCount: 4
keynoteSpeakersTitle: "Keynote speakers"
keynoteSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Sabancı University Performing Arts Center (SGM)"
eventLocationLink: ""
eventStreetAddress: "Universite Cad. No 27"
eventAddressLocality: "Tuzla"
eventAddressLocalityRegion: "Istanbul"
eventPostalCode: "34956"
eventAddressCountry: "Turkey"
eventStartTime: "2020-09-03T09:00"
eventDoorTime: "09:00"
eventEndTime: "2020-09-05T17:00"
eventPlaceCoordinates: "40.8928831, 29.3748667"
mapCenterCoordinates: "40.8928831, 29.3748667"
mapMobileCenterCoordinates: "40.8928831, 29.3748667"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "sgm_in1.jpg"
venueSmallImage1: "sgm_in2.jpg"
venueSmallImage2: "sgm_in3.jpg"
venueSmallImage3: "sgm_hall1.jpg"
venueSmallImage4: "sgm_hall2.jpg"
venueSmallImage5: "sgm_out1.jpg"
venueSmallImage6: "sgm_out2.jpg"
venueTitle: "Sabancı University Performing Arts Center (SGM)"
venueFeatures: ["In the Sabanci University campus", "Within walking distance to cafeteria and dormitories", "Large capacity"]

# Tweets Feed Block
tweetsFeedImage: "handsup.jpg"
tweetsFeedTitle: "Stay tuned"
twitterHashTag: "HIBIT2020"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Student Registration"
ticketsInfo: "Registration grants access to conference section, coffee brakes, lunch and gala dinner. On-campus accommodation at student dormitories is included with the [registration + accommodation] fee. The rooms are shared by two students. Roommate arrangements can be made upon request."
ticketsOffers:
 -
  name: "Student Early Bird Registration"
  price: "350"
  priceCurrency: "TL"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-06-30T23:59"
 -
  name: "Student Early Bird Registration + Dormitory Accommodation"
  price: "650"
  priceCurrency: "TL"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-06-30T23:59"
 -
  name: "Student Late Registration"
  price: "450"
  priceCurrency: "TL"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-08-15T23:59"
 -
  name: "Student Late Registration + Dormitory Accommodation"
  price: "750"
  priceCurrency: "TL"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-08-15T23:59"

academicsTitle: "Academic Registration"
academicsInfo: "Registration grants access to conference section, coffee brakes, lunch and gala dinner. On-campus accommodation at student dormitories is included with the registration + accommodation option. Academics will have an option to choose single or double room."
academics:
 -
  name: "Academic Early Bird Registration"
  price: "500"
  priceCurrency: "TL"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-06-30T23:59"
 -
  name: "Academic Early Bird Registration + Dormitory Accommodation"
  price: "800"
  priceCurrency: "TL"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-06-30T23:59"
 -
  name: "Academic Late Registration"
  price: "650"
  priceCurrency: "TL"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-08-15T23:59"
 -
  name: "Academic Late Registration + Dormitory Accommodation"
  price: "950"
  priceCurrency: "TL"
  ticketsNumber: "20"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-08-15T23:59"


corporateTitle: "Corporate Registration"
corporateInfo: "Registration grants access to conference section, coffee brakes, lunch and gala dinner. Accommodation os NOT included in the registration fee."
corporate:
 -
  name: "Corporate Registration"
  price: "800"
  priceCurrency: "TL"
  ticketsNumber: "100"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Register Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2019-12-01T10:00"
  validThrough: "2020-08-15T23:59"


# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=hibit2020", icon: "twitter"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:hibit2020@gmail.com", text: "hibit2020@gmail.com"}
 

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.8928831, 29.3748667"
logisticsMapMobileCenterCoordinates: "40.8928831, 29.3748667"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "ist2.jpg"
directionDetailsTitle: "Coming to the campus"
directionDetailsCards:
 - {title: "From Istanbul Airport", information: 'Istanbul Airport is far away from the campus and city centres. There is a shuttle service from Ist. Airport to various central locations. Information is listed <a href="https://hava.ist/en" target="_blank">here.</a> If you are coming directly to campus, the most hassle free way is taking the shuttle to Sabiha Gokcen Airport and taking a taxi ride.'}
 - {title: "From Sabiha Gokcen Airport", information: 'Because Sabancı University is very close to the airport and there is no direct or useful indirect public transportation, we kindly recommend you to take a taxi. It takes about 20 minutes.'}
 - {title: "In-city transit", information: 'There is a regular shuttle service from Kadıköy and Levent (central locations in European and Asian sides). On these shuttles, it is written Gürsel in big letters. For the timetable please click <a href="http://www.sabanciuniv.edu/en/transportation/shuttle-hours" target="_blank">here.</a>'}
 - {title: "Hotels", information: 'Closest hotel to the campus is <a href="http://www.cpistanbulasia.com/" target="_blank">Crowne Plaza Hotel.</a>'}


# Poster list Block
posterListTitle: "Posters at HIBIT 2020"
posterCards:
 - {title: "Lorem ipsum article title dolor sit amet", authors: "Oznur Tastan, Ogun Adebali, Tuvan Gezer", abstract: 'Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract '}
 - {title: "Lorem ipsum article title dolor sit amet", authors: "Oznur Tastan, Ogun Adebali, Tuvan Gezer", abstract: 'Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract '}
 - {title: "Lorem ipsum article title dolor sit amet", authors: "Oznur Tastan, Ogun Adebali, Tuvan Gezer", abstract: 'Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract '}
 - {title: "Lorem ipsum article title dolor sit amet", authors: "Oznur Tastan, Ogun Adebali, Tuvan Gezer", abstract: 'Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract '}
 - {title: "Lorem ipsum article title dolor sit amet", authors: "Oznur Tastan, Ogun Adebali, Tuvan Gezer", abstract: 'Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract '}
 - {title: "Lorem ipsum article title dolor sit amet", authors: "Oznur Tastan, Ogun Adebali, Tuvan Gezer", abstract: 'Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract Paper abstract '}

#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Keynote Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2020-09-03T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "40.8928831, 29.3748667"
hackathonMapCenterCoordinates: "40.8928831, 29.3748667"
hackathonMapMobileCenterCoordinates: "40.8928831, 29.3748667"
